spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}

app.cors.allowedOrigins: https://s-assesment-web.herokuapp.com